version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - $HOME/docker/volumes/golang-rest-api-example-postgres:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  app:
    build: .
    environment:
      APP_DB_HOST: postgres
      APP_DB_PORT: 5432
      APP_DB_NAME: docker
      APP_DB_USER: docker
      APP_DB_PASS: docker
    volumes:
      - $HOME/docker/volumes/golang-rest-api-example:/app/store
    ports:
      - 80:8080
    depends_on:
      - postgres